name: MEffectUI
api: 5.0.0
version: 1.0.0
main: MagmaZ3637\Meffect\Main
author: MagmaZ3637
description: MEffectUI is a PocketMine plugin that can apply various effects to players based on their permissions.

commands:
  meffectui:
    description: §eOpen Effect UI
    permission: meffect.use
    aliases: ["meffect", "meui"]

permissions:
  meffect.use:
    description: For UI
    default: true
  effect.regen:
    default: op
